name: generator-saas-local

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        NODE_VERSION: 22-alpine
        PNPM_VERSION: 10.17.1
    working_dir: /app
    volumes:
      - ./:/app # seu código
      - /app/node_modules # volume anônimo p/ não poluir o host
      - next-cache:/app/.next # cache do Next
      - pnpm-store:/root/.local/share/pnpm/store # cache do pnpm
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
      WATCHPACK_POLLING: "true" # útil no Docker Desktop/WSL
      PORT: "3000"
      HOSTNAME: "0.0.0.0"
    command: pnpm dev # (pode omitir; já é o CMD do stage dev)
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-root}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  next-cache:
  pnpm-store:
