global:
  resolve_timeout: 5m

route:
  receiver: "default"
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 4h

receivers:
  - name: "default"
    # Exemplo com log; para e-mail/Slack/Webhook, adicione aqui:
    # slack_configs:
    #   - api_url: ${SLACK_WEBHOOK_URL}
    #     channel: "#alerts"
