import clsx from 'clsx';
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins } from "next/font/google";
import "./globals.css";
import AppContextProvider from "./AppContext";
import { ClerkProvider } from "@clerk/nextjs";

// Tradução
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import {ReactNode} from 'react';

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Local Font
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});


type Props = {
  children: ReactNode;
};

// Root Layout
export default async function RootLayout({children}: Props){
  // Locate
  const locale = await getLocale();
  // Message
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <NextIntlClientProvider messages={messages}>
        <ClerkProvider>
          <AppContextProvider>
            <body className={poppins.variable}>{children}</body>
          </AppContextProvider>
        </ClerkProvider>
      </NextIntlClientProvider>
    </html>
  );
}
